# Generated by Django 3.1 on 2020-09-06 05:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20200906_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.TextField(default='new data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
